### ISSUE TITLE
gemini-2.0-flash-exp can't change default voice 

### ISSUE THREAD

**Issue by peoplesdriver** [TEN-framework/TEN-Agent#498]
### Description

i have changed the voice in the proprieties field but it didn't change, i have tried all 5 voices

### Environment

windows wsl2 ubuntu 24.04

### Steps to reproduce

change the voice in the gemini v2v proprieties

### Expected behavior

the voice to change

### Severity

Critical

**Comment by plutoless** [comment]
it's a known issue that currently setting voice with google-genai lib will result in an error, that's why we commented it out for now.
https://github.com/TEN-framework/TEN-Agent/blob/470b44169ecc9dfcba57c32b3f1598cfa7c1de02/agents/ten_packages/extension/gemini_v2v_python/extension.py#L438

I will update here once google fix it.

**Comment by plutoless** [comment]
fixed in efa194ede866eea1e368c3a899c102b85a5b3e87
